- name: Index
  filename: Index.page.md
- name: BaRS Deployment Guide
  filename: Deploy.page.md
- name: Key Deployment Activities
  filename: Key Deployment Activities.page.md
- name: Roles and Responsibilities
  filename: Roles and Responsibilities.page.md
- name: Directory of Service (DoS) Configuration
  filename: Directory of Service (DoS) Configuration.page.md

